### ISSUE TITLE
[Back-End] - Create/Edit/Delete Public Posts (Text & Images)

### ISSUE THREAD

**Issue by toado** [robertavichm/CMPUT-404-PROJECT-WORK-W21#2]
### User Stories

- [ ] **[US#1]** - As an author I want to make public posts.
- [ ] **[US#2]** - As an author I want to edit public posts.
- [ ] **[US#3]** - As an author, posts I create can link to images.
- [ ] **[US#4]** - As an author, posts I create can be images.
- [ ] **[US#10]** - As an author, posts I make can be in simple plain text.
- [ ] **[US#11]** - As an author, posts I make can be in CommonMark
 - [ ] **[US#17]** - As an author, I want to delete my own public posts.

### Tests
- [ ] Create appropriate tests for respective POST/GET/PUT/DELETE
