### ISSUE TITLE
[Back-End] - Authentication

### ISSUE THREAD

**Issue by toado** [robertavichm/CMPUT-404-PROJECT-WORK-W21#3]
### User Stories
- [ ] **[US#27]** - As a server admin, I want to OPTIONALLY be able allow users to sign up but require my OK to finally be on my server
- [ ] **[US#38]** - As a server admin, I want to be able to add nodes to share with
- [ ] **[US#39]** - As a server admin, I want to be able to remove nodes and stop sharing with them.
- [ ] **[US#40]** - As a server admin, I can limit nodes connecting to me via authentication.
- [ ] **[US#41]** - As a server admin, node to node connections can be authenticated with HTTP Basic Auth
- [ ] **[US#42]** - As a server admin, I can disable the node to node interfaces for connections that are not authenticated!
