### ISSUE TITLE
[Back-End] - Befriending 

### ISSUE THREAD

**Issue by Ny-Tran** [robertavichm/CMPUT-404-PROJECT-WORK-W21#4]
### User Stories
- [ ] **[US#18]** - As an author, I want to befriend local authors
- [ ] **[US#19]** - As an author, I want to befriend remote authors
- [ ] **[US#23]** - As an author, I want un-befriend local and remote authors
- [ ] **[US#36]** - As an author, I want to know if I have friend requests
